DFRobotMaqueenPlusV2.init()
basic.showIcon(IconNames.Asleep)
basic.forever(function () {
    DFRobotMaqueenPlusV2.showColor(0xff0000)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 237)
    basic.pause(500)
    DFRobotMaqueenPlusV2.showColor(0xff0000)
    maqueen.motorStop(maqueen.Motors.M1)
    basic.pause(1000)
})
